# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FNKncGR3Io71Wks4CnsXxWfWIwdLFKS6
"""

# ================================
# app.py - Final NLP Project Dashboard
# ================================
import streamlit as st
import pandas as pd
from nrclex import NRCLex
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import nltk

import base64

# Function to set custom background with a frosted-glass overlay
def set_background(image_file):
    with open(image_file, "rb") as f:
        data = f.read()
    b64 = base64.b64encode(data).decode()

    st.markdown(f"""
        <style>
        .stApp {{
            background-image: url("data:image/jpg;base64,{b64}");
            background-size: cover;
            background-position: center;
            background-attachment: fixed;
        }}
        h1, h2, h3, p, label {{
            color: #ffffff !important;
            text-shadow: 1px 1px 3px rgba(0,0,0,0.9);
        }}
        </style>
    """, unsafe_allow_html=True)
# Call Background Function
set_background("samuel-regan-asante-wMkaMXTJjlQ-unsplash.jpg")

# Download necessary NLTK data (only once)
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('punkt', quiet=True)

# ================================
# Page Setup
# ================================
st.set_page_config(page_title="Sentiment & Emotion Analyzer", layout="centered")
# Create a glass-effect container for all content
st.markdown("""
    <style>
    .glass-box {
        background: rgba(0, 0, 0, 0.55);
        backdrop-filter: blur(14px);
        -webkit-backdrop-filter: blur(14px);
        border-radius: 18px;
        padding: 40px 50px;
        margin: 50px auto;
        max-width: 1050px;
        box-shadow: 0 8px 40px rgba(0,0,0,0.6);
    }
    </style>
    <div class="glass-box">
""", unsafe_allow_html=True)

# Main content inside glass box
st.title("🎬 IMDb Movie Review - NLP Sentiment & Emotion Analyzer")
st.write("Analyze any movie review — get its **sentiment**, **dominant emotion**, and **visual insights**!")

# ================================
# Load Preprocessed Dataset
# ================================
import gdown
import os

file_id = "1c-6qg1kGsuDrNXS9iCH4L1ryqiARMAUM"
url = f"https://drive.google.com/uc?id={file_id}"

# Download file if not already present
if not os.path.exists("IMDB_Dataset.csv"):
    gdown.download(url, "IMDB_Dataset.csv", quiet=False)

data = pd.read_csv("IMDB_Dataset.csv", on_bad_lines='skip')

data = data.sample(5000, random_state=42)

# Prepare training data
from sklearn.model_selection import train_test_split
X = data['review']
y = data['sentiment']

# Vectorize text
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))
X_tfidf = tfidf.fit_transform(X)

# Train model
model = LogisticRegression(max_iter=200)
model.fit(X_tfidf, y)

# ================================
# Input Box
# ================================
user_input = st.text_area("✍️ Enter a movie review below:", height=150)

if st.button("Analyze Review"):
    if user_input.strip() == "":
        st.warning("Please type a review first!")
    else:
        # Predict sentiment
        user_tfidf = tfidf.transform([user_input])
        sentiment = model.predict(user_tfidf)[0]

        # Emotion detection
        emo = NRCLex(user_input)
        scores = emo.raw_emotion_scores
        dominant_emotion = max(scores.items(), key=lambda x: x[1])[0] if scores else "neutral"

        # ================================
        # Display results
        # ================================
        st.subheader("🧠 Analysis Result")
        st.write(f"**Sentiment:** {sentiment.capitalize()}")
        st.write(f"**Dominant Emotion:** {dominant_emotion.capitalize()}")

        # Add animations for fun effect
        if sentiment == "positive":
            st.balloons()
        elif sentiment == "negative":
            st.snow()

        # ================================
        # Emotion Breakdown Chart
        # ================================
        if scores:
            st.subheader("🎭 Emotion Breakdown")
            emo_df = pd.DataFrame(scores.items(), columns=['Emotion', 'Score']).sort_values(by='Score', ascending=False)
            st.bar_chart(emo_df.set_index('Emotion'))
        else:
            st.info("No clear emotions detected for this text.")

        # ================================
        # 🎬 Movie Recommendation Section
        # ================================
        st.subheader("🍿 Movie Recommendations for You")

        # Movie lists based on mood/sentiment
        movie_recs = {
            "positive": [
                "The Pursuit of Happyness", "Forrest Gump", "Interstellar", "Inside Out",
                "Coco", "La La Land", "3 Idiots", "Zindagi Na Milegi Dobara"
            ],
            "negative": [
                "Joker", "The Shawshank Redemption", "Fight Club", "The Green Mile",
                "Requiem for a Dream", "Grave of the Fireflies", "Manchester by the Sea", "The Whale"
            ],
            "neutral": [
                "Inception", "Tenet", "The Prestige", "Arrival",
                "The Matrix", "Source Code", "Her", "Eternal Sunshine of the Spotless Mind"
            ]
        }

        # Select list based on sentiment
        recs = movie_recs.get(sentiment.lower(), movie_recs["neutral"])

        # Display in fun layout
        cols = st.columns(4)
        for i, movie in enumerate(recs[:8]):
            with cols[i % 4]:
                st.markdown(f"🎞️ **{movie}**")

        st.success("Hope these movies match your mood! 🍿")

# ================================
# WordCloud Visualization
# ================================
st.subheader("🌈 WordCloud of Positive vs Negative Reviews")

pos_text = " ".join(data[data['sentiment'] == 'positive']['review'])
neg_text = " ".join(data[data['sentiment'] == 'negative']['review'])

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
axes[0].imshow(WordCloud(width=600, height=400, background_color='white', colormap='Greens').generate(pos_text), interpolation='bilinear')
axes[0].set_title('Positive Reviews')
axes[0].axis('off')

axes[1].imshow(WordCloud(width=600, height=400, background_color='white', colormap='Reds').generate(neg_text), interpolation='bilinear')
axes[1].set_title('Negative Reviews')
axes[1].axis('off')

st.pyplot(fig)
st.markdown("</div>", unsafe_allow_html=True)
