# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FNKncGR3Io71Wks4CnsXxWfWIwdLFKS6
"""

# ================================
# app.py - Final NLP Project Dashboard
# ================================

import streamlit as st
import pandas as pd
from nrclex import NRCLex
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import nltk

# Download necessary NLTK data (only once)
nltk.download('punkt', quiet=True)

# ================================
# Page Setup
# ================================
st.set_page_config(page_title="Sentiment & Emotion Analyzer", layout="centered")
st.title("🎬 IMDb Movie Review - NLP Sentiment & Emotion Analyzer")
st.write("Analyze any movie review — get its **sentiment**, **dominant emotion**, and **visual insights**!")

# ================================
# Load Preprocessed Dataset
# ================================
url = "https://raw.githubusercontent.com/RohitInfinite/NLP-Sentiment-Emotion-Analyzer/main/IMDB%20Dataset.csv"
data = pd.read_csv(url)
data = data.sample(5000, random_state=42)

# Prepare training data
from sklearn.model_selection import train_test_split
X = data['review']
y = data['sentiment']

# Vectorize text
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))
X_tfidf = tfidf.fit_transform(X)

# Train model
model = LogisticRegression(max_iter=200)
model.fit(X_tfidf, y)

# ================================
# Input Box
# ================================
user_input = st.text_area("✍️ Enter a movie review below:", height=150)

if st.button("Analyze Review"):
    if user_input.strip() == "":
        st.warning("Please type a review first!")
    else:
        # Predict sentiment
        user_tfidf = tfidf.transform([user_input])
        sentiment = model.predict(user_tfidf)[0]

        # Emotion detection
        emo = NRCLex(user_input)
        scores = emo.raw_emotion_scores
        dominant_emotion = max(scores.items(), key=lambda x: x[1])[0] if scores else "neutral"

        # ================================
        # Display results
        # ================================
        st.subheader("🧠 Analysis Result")
        st.write(f"**Sentiment:** {sentiment.capitalize()}")
        st.write(f"**Dominant Emotion:** {dominant_emotion.capitalize()}")

        # Add animations for fun effect
        if sentiment == "positive":
            st.balloons()
        elif sentiment == "negative":
            st.snow()

        # ================================
        # Emotion Breakdown Chart
        # ================================
        if scores:
            st.subheader("🎭 Emotion Breakdown")
            emo_df = pd.DataFrame(scores.items(), columns=['Emotion', 'Score']).sort_values(by='Score', ascending=False)
            st.bar_chart(emo_df.set_index('Emotion'))
        else:
            st.info("No clear emotions detected for this text.")

        # ================================
        # 🎬 Movie Recommendation Section
        # ================================
        st.subheader("🍿 Movie Recommendations for You")

        # Movie lists based on mood/sentiment
        movie_recs = {
            "positive": [
                "The Pursuit of Happyness", "Forrest Gump", "Interstellar", "Inside Out",
                "Coco", "La La Land", "3 Idiots", "Zindagi Na Milegi Dobara"
            ],
            "negative": [
                "Joker", "The Shawshank Redemption", "Fight Club", "The Green Mile",
                "Requiem for a Dream", "Grave of the Fireflies", "Manchester by the Sea", "The Whale"
            ],
            "neutral": [
                "Inception", "Tenet", "The Prestige", "Arrival",
                "The Matrix", "Source Code", "Her", "Eternal Sunshine of the Spotless Mind"
            ]
        }

        # Select list based on sentiment
        recs = movie_recs.get(sentiment.lower(), movie_recs["neutral"])

        # Display in fun layout
        cols = st.columns(4)
        for i, movie in enumerate(recs[:8]):
            with cols[i % 4]:
                st.markdown(f"🎞️ **{movie}**")

        st.success("Hope these movies match your mood! 🍿")

# ================================
# WordCloud Visualization
# ================================
st.subheader("🌈 WordCloud of Positive vs Negative Reviews")

pos_text = " ".join(data[data['sentiment'] == 'positive']['review'])
neg_text = " ".join(data[data['sentiment'] == 'negative']['review'])

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
axes[0].imshow(WordCloud(width=600, height=400, background_color='white', colormap='Greens').generate(pos_text), interpolation='bilinear')
axes[0].set_title('Positive Reviews')
axes[0].axis('off')

axes[1].imshow(WordCloud(width=600, height=400, background_color='white', colormap='Reds').generate(neg_text), interpolation='bilinear')
axes[1].set_title('Negative Reviews')
axes[1].axis('off')

st.pyplot(fig)
